### Generate Access Token
POST http://localhost:8000/api/v1/iam/login
Accept: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

> {%
    client.global.set("access_token", response.body.token);
%}

### Refresh Access Token
GET http://localhost:8000/api/v1/iam/refresh
Accept: application/json

> {%
    client.global.set("access_token", response.body.token);
%}

### List All Users
GET http://localhost:8000/api/v1/iam/user/list
Accept: application/json
Authorization: Bearer {{access_token}}

### Get User by ID
GET http://localhost:8000/api/v1/iam/user/4d07ee63-ad16-4c6c-b8bb-2b956580bef5
Accept: application/json
Authorization: Bearer {{access_token}}

### Create New User
POST localhost:8000/api/v1/iam/user
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "email": "caroline@mail.com",
    "name": "Caroline Nascimento",
    "password": "123ABC#",
    "role": "AN",
    "listIdSector": ["5e48dd22-69bd-4db1-9e33-8f02104d20ad", "99fb6b9a-1485-4fd3-94f7-e1680103867f", "c969a4e8-994e-4214-8218-9a40f1773361"]
}

### Update User
PUT localhost:8000/api/v1/iam/user/00351a51-ac4c-4c83-9e15-edf0beb64e38
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "email": "caroline@mail.com",
    "name": "Caroline Gomes do Nascimento",
    "role": "AN",
    "listIdSector": ["5e48dd22-69bd-4db1-9e33-8f02104d20ad", "99fb6b9a-1485-4fd3-94f7-e1680103867f", "c969a4e8-994e-4214-8218-9a40f1773361"]
}

### Delete User
DELETE localhost:8000/api/v1/iam/user/59703a4d-e067-4fdc-8f87-82600d7764f2
Accept: application/json
Authorization: Bearer {{access_token}}

### List All Business Sector
GET http://localhost:8000/api/v1/sector/list
Accept: application/json
Authorization: Bearer {{access_token}}

### Get Business Sector
GET http://localhost:8000/api/v1/sector/5e48dd22-69bd-4db1-9e33-8f02104d20ad
Accept: application/json
Authorization: Bearer {{access_token}}

### Create New Business Sector
POST http://localhost:8000/api/v1/sector
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "sector_name": "Insurance Sector"
}

### Update Business Sector
PUT localhost:8000/api/v1/sector/5e48dd22-69bd-4db1-9e33-8f02104d20ad
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "sector_name": "Public Sector"
}

### Delete Business Sector
DELETE localhost:8000/api/v1/sector/5e48dd22-69bd-4db1-9e33-8f02104d20ad
Accept: application/json
Authorization: Bearer {{access_token}}

### Upload a Project File
POST http://localhost:8000/api/v1/project/upload
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="file"; filename="proj_upload_two.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./proj_upload_two.xlsx
--boundary--

### Upload a Resume File
POST http://localhost:8000/api/v1/resume/upload
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{access_token}}

--boundary
Content-Disposition: form-data; name="file"; filename="Jorge-CV.pdf"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./Jorge-CV.pdf
--boundary--

### List all customers by endpoint
GET localhost:8000/api/v1/customer/list
Accept: application/json
Authorization: Bearer {{access_token}}
