### IAM
###
POST http://localhost:8000/api/v1/iam/login
Accept: application/json

{
    "email": "admin@mail.com",
    "password": "admin"
}

> {%
    client.global.set("access_token", response.body.token);
%}

###
POST http://localhost:8000/api/v1/iam/login
Accept: application/json

{
    "email": "caio@mail.com",
    "password": "123ABC#"
}

> {%
    client.global.set("access_token", response.body.token);
%}

###
GET http://localhost:8000/api/v1/iam/refresh
Accept: application/json

> {%
    client.global.set("access_token", response.body.token);
%}

###
GET http://localhost:8000/api/v1/iam/user/list
Accept: application/json
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/v1/iam/user/59703a4d-e067-4fdc-8f87-82600d7764f2
Accept: application/json
Authorization: Bearer {{access_token}}

###
POST localhost:8000/api/v1/iam/user
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "email": "caroline@mail.com",
    "name": "Caroline Nascimento",
    "password": "123ABC#",
    "role": "AN"
}


### Business Sector
###
GET http://localhost:8000/api/v1/sector/list
Accept: application/json
Authorization: Bearer {{access_token}}

###
GET http://localhost:8000/api/v1/sector/5e48dd22-69bd-4db1-9e33-8f02104d20ad
Accept: application/json
Authorization: Bearer {{access_token}}

###
POST http://localhost:8000/api/v1/sector
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "sector_name": "Insurance Sector"
}

###
PUT localhost:8000/api/v1/sector/5e48dd22-69bd-4db1-9e33-8f02104d20ad
Accept: application/json
Authorization: Bearer {{access_token}}

{
    "sector_name": "Public Sector"
}

###
DELETE localhost:8000/api/v1/sector/5e48dd22-69bd-4db1-9e33-8f02104d20ad
Accept: application/json
Authorization: Bearer {{access_token}}
