### Generate Access Token
POST http://localhost:8000/api/v1/iam/login
Accept: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

> {%
    client.global.set("access_token", response.body.token);
%}

### Refresh Access Token
POST http://localhost:8000/api/v1/iam/refresh
Accept: application/json

> {%
    client.global.set("access_token", response.body.token);
%}
### Upload a Tender File
POST http://localhost:8000/api/v1/tender/upload
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="files"; filename="pp.pdf"
Content-Type: application/pdf

< ./pp.pdf

--boundary
Content-Disposition: form-data; name="files"; filename="pp.pdf"
Content-Type: application/pdf

< ./pp.pdf

--boundary--

### Evaluate Tender
POST http://localhost:8000/api/v1/tender/evaluate/f17afd76-da1d-4b1f-876b-22af442fba3f
Authorization: Bearer {{access_token}}
Accept: application/json

### Get all tenders
GET http://localhost:8000/api/v1/tender/list
Authorization: Bearer {{access_token}}
Accept: application/json

### Get tender by ID
GET http://localhost:8000/api/v1/tender/f17afd76-da1d-4b1f-876b-22af442fba3f
Authorization: Bearer {{access_token}}
Accept: application/json

### Get tender candidates
GET http://localhost:8000/api/v1/tender/candidate/499d5251-8feb-4b79-8e77-d94628e98f28
Authorization: Bearer {{access_token}}
Accept: application/json

